# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2016, 1, 22, 10, 39, 41, 879000))),
            ],
            options={
                'db_table': 'interests',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name=b'2016-01-22')),
                ('occupation', models.TextField(max_length=100)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.Interest')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
