# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 1, 22, 11, 6, 50, 882000)),
        ),
    ]
