# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_auto_20160122_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(verbose_name=b'2016-01-22'),
        ),
    ]
