# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0007_auto_20160122_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(default=b'2016-01-24'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=b'2016-01-24'),
        ),
    ]
